"""ZatGo POS settings manifest for the configuration center."""

from __future__ import annotations

MANIFEST = {
    "app_key": "zatgo_pos",
    "title": "ZatGo POS",
    "version": "0.1.0",
    "icon": "retail",
    "category": "Sales",
    "menu_order": 10,
    "enabled": 1,
    "visible": 1,
    "roles": "System Manager,ZG Application Admin,ZG Company Admin",
    "depends_on": "",
    "description": "Point of sale configuration",
    "settings_route": "zg-core",
    "sections": [
        {
            "section_key": "general",
            "label": "General",
            "icon": "setting",
            "sort_order": 10,
            "link_doctype": "ZG System Settings",
            "component": "",
        },
        {
            "section_key": "module_preferences",
            "label": "Module Preferences",
            "icon": "list",
            "sort_order": 20,
            "component": "module_preferences",
            "defaults_json": {
                "enable_kitchen": 1,
                "enable_qr_ordering": 0,
                "enable_delivery": 1,
                "enable_loyalty": 0,
                "enable_gift_card": 0,
                "enable_offline_mode": 0,
                "enable_discounts": 1,
                "enable_waiter": 1,
                "enable_token_system": 0,
                "enable_self_checkout": 0,
                "enable_customer_display": 0,
            },
        },
        {
            "section_key": "receipt",
            "label": "Receipt Settings",
            "icon": "printer",
            "sort_order": 30,
            "link_doctype": "ZG Printer Settings",
            "component": "",
        },
        {
            "section_key": "printers",
            "label": "Printer Settings",
            "icon": "printer",
            "sort_order": 40,
            "link_doctype": "ZG Printer Settings",
            "component": "",
        },
        {
            "section_key": "payments",
            "label": "Payment Methods",
            "icon": "money",
            "sort_order": 50,
            "link_doctype": "ZG Payment Settings",
            "component": "",
        },
        {
            "section_key": "offline",
            "label": "Offline Sync",
            "icon": "refresh",
            "sort_order": 60,
            "link_doctype": "ZG Sync Settings",
            "component": "",
        },
        {
            "section_key": "table_management",
            "label": "Table Management",
            "icon": "table",
            "sort_order": 70,
            "component": "pending",
            "description": "Phase 2 — floors, tables, QR, merge/split",
        },
        {
            "section_key": "floor_management",
            "label": "Floor Management",
            "icon": "organization",
            "sort_order": 80,
            "component": "pending",
        },
        {
            "section_key": "kitchen_settings",
            "label": "Kitchen Settings",
            "icon": "cuisine",
            "sort_order": 90,
            "component": "pending",
        },
        {
            "section_key": "about",
            "label": "About",
            "icon": "info",
            "sort_order": 200,
            "component": "about",
        },
    ],
}
