"""Default Electron / Flutter / Web client applications for a site."""

from __future__ import annotations

# Site-scoped client products (NOT Frappe custom apps).
# api_product maps to zatgo_core.api.v1.<product> when set.
# Domain exceptions (own APIs; leave api_product empty):
#   Tracker → tracker.api.v1.*
#   Chat AI → chat_ai.api.*
DEFAULT_CLIENT_APPS: tuple[dict[str, object], ...] = (
    {
        "app_key": "zatgo_pos",
        "title": "ZatGo POS",
        "platform": "Electron",
        "enabled": 1,
        "api_product": "resto_pos",
        "description": "Point of sale desktop client",
    },
    {
        "app_key": "admin_console",
        "title": "Admin Console",
        "platform": "Electron",
        "enabled": 1,
        "api_product": "admin",
        "description": "Site administration desktop client",
    },
    {
        "app_key": "accounting_desktop",
        "title": "Accounting Desktop",
        "platform": "Electron",
        "enabled": 0,
        "api_product": "accounting",
        "description": "Accounting desktop client",
    },
    {
        "app_key": "warehouse_desktop",
        "title": "Warehouse Desktop",
        "platform": "Electron",
        "enabled": 0,
        "api_product": "warehouse",
        "description": "Warehouse desktop client",
    },
    {
        "app_key": "fleet_desktop",
        "title": "Fleet Desktop",
        "platform": "Electron",
        "enabled": 0,
        "api_product": "fleet",
        "description": "Fleet desktop client",
    },
    {
        "app_key": "tracker_desktop",
        "title": "Tracker Desktop",
        "platform": "Electron",
        "enabled": 1,
        "api_product": "",
        "description": "Project Tracker desktop (tracker.api.v1.*)",
    },
    {
        "app_key": "report_studio",
        "title": "Report Studio",
        "platform": "Electron",
        "enabled": 0,
        "api_product": "bi",
        "description": "BI / report studio desktop client",
    },
    {
        "app_key": "kitchen",
        "title": "Kitchen",
        "platform": "Flutter",
        "enabled": 1,
        "api_product": "resto_pos",
        "description": "Kitchen display Flutter app",
    },
    {
        "app_key": "delivery",
        "title": "Delivery",
        "platform": "Flutter",
        "enabled": 1,
        "api_product": "delivery",
        "description": "Delivery Flutter app",
    },
    {
        "app_key": "tracker",
        "title": "Tracker",
        "platform": "Flutter",
        "enabled": 1,
        "api_product": "",
        "description": "Project Tracker Flutter app (tracker.api.v1.*)",
    },
    {
        "app_key": "go_van",
        "title": "Go Van",
        "platform": "Flutter",
        "enabled": 0,
        "api_product": "go_van",
        "description": "Go Van Flutter app",
    },
    {
        "app_key": "service",
        "title": "Service",
        "platform": "Flutter",
        "enabled": 0,
        "api_product": "service",
        "description": "Service Flutter app",
    },
    {
        "app_key": "crm",
        "title": "CRM",
        "platform": "Flutter",
        "enabled": 0,
        "api_product": "crm",
        "description": "CRM Flutter scaffold",
    },
    {
        "app_key": "hr",
        "title": "HR",
        "platform": "Flutter",
        "enabled": 0,
        "api_product": "hr",
        "description": "HR Flutter scaffold",
    },
    {
        "app_key": "warehouse",
        "title": "Warehouse",
        "platform": "Flutter",
        "enabled": 0,
        "api_product": "warehouse",
        "description": "Warehouse Flutter scaffold",
    },
    {
        "app_key": "admin_portal",
        "title": "Admin Portal",
        "platform": "Web",
        "enabled": 1,
        "api_product": "admin",
        "description": "Admin Next.js portal",
    },
    {
        "app_key": "tracker_web",
        "title": "Tracker Web",
        "platform": "Web",
        "enabled": 1,
        "api_product": "",
        "description": "Project Tracker web (tracker.api.v1.*)",
    },
    {
        "app_key": "customer_portal",
        "title": "Customer Portal",
        "platform": "Web",
        "enabled": 0,
        "api_product": "customer_portal",
        "description": "Customer Next.js portal",
    },
    {
        "app_key": "vendor_portal",
        "title": "Vendor Portal",
        "platform": "Web",
        "enabled": 0,
        "api_product": "vendor_portal",
        "description": "Vendor Next.js portal",
    },
    {
        "app_key": "crm_portal",
        "title": "CRM Portal",
        "platform": "Web",
        "enabled": 0,
        "api_product": "crm",
        "description": "CRM Next.js portal",
    },
    {
        "app_key": "bi_dashboard",
        "title": "BI Dashboard",
        "platform": "Web",
        "enabled": 0,
        "api_product": "bi",
        "description": "BI dashboard web client",
    },
    {
        "app_key": "documentation",
        "title": "Documentation",
        "platform": "Web",
        "enabled": 0,
        "api_product": "documentation",
        "description": "Documentation Next.js site",
    },
)
