"""Old method paths of the apps merged into zatgo_core -> their new paths,
for clients built against the old apps (e.g. @zatgo/erpnext's TrackerApi
still calls tracker.api.v1.*). Used as hooks.py override_whitelisted_methods;
the old paths are gated by the module switches like the new ones
(services/bundled_apps.gate_module_api). Generated from the modules' api/
packages -- regenerate when a whitelisted function is added there."""

OLD_METHOD_PATHS = {
    "chat_ai.api.admin.get_dashboard_summary": "zatgo_core.chat_ai.api.admin.get_dashboard_summary",
    "chat_ai.api.admin.list_errors": "zatgo_core.chat_ai.api.admin.list_errors",
    "chat_ai.api.admin.ping_provider": "zatgo_core.chat_ai.api.admin.ping_provider",
    "chat_ai.api.chat.send": "zatgo_core.chat_ai.api.chat.send",
    "chat_ai.api.chat.cancel": "zatgo_core.chat_ai.api.chat.cancel",
    "chat_ai.api.chat.history": "zatgo_core.chat_ai.api.chat.history",
    "chat_ai.api.chat.list_sessions": "zatgo_core.chat_ai.api.chat.list_sessions",
    "chat_ai.api.chat.clear": "zatgo_core.chat_ai.api.chat.clear",
    "chat_ai.api.chat.rename": "zatgo_core.chat_ai.api.chat.rename",
    "chat_ai.api.chat.set_mode": "zatgo_core.chat_ai.api.chat.set_mode",
    "chat_ai.api.chat.archive": "zatgo_core.chat_ai.api.chat.archive",
    "chat_ai.api.chat.pin": "zatgo_core.chat_ai.api.chat.pin",
    "chat_ai.api.chat.delete_session": "zatgo_core.chat_ai.api.chat.delete_session",
    "chat_ai.api.chat.search_sessions": "zatgo_core.chat_ai.api.chat.search_sessions",
    "chat_ai.api.chat.list_commands": "zatgo_core.chat_ai.api.chat.list_commands",
    "chat_ai.api.chat.new_session": "zatgo_core.chat_ai.api.chat.new_session",
    "chat_ai.api.chat.set_language": "zatgo_core.chat_ai.api.chat.set_language",
    "chat_ai.api.chat.get_ui_locale": "zatgo_core.chat_ai.api.chat.get_ui_locale",
    "chat_ai.api.platform.chat_message": "zatgo_core.chat_ai.api.platform.chat_message",
    "chat_ai.api.platform.chat_session_new": "zatgo_core.chat_ai.api.platform.chat_session_new",
    "chat_ai.api.platform.chat_session_list": "zatgo_core.chat_ai.api.platform.chat_session_list",
    "chat_ai.api.platform.chat_session_rename": "zatgo_core.chat_ai.api.platform.chat_session_rename",
    "chat_ai.api.platform.chat_session_archive": "zatgo_core.chat_ai.api.platform.chat_session_archive",
    "chat_ai.api.platform.chat_history": "zatgo_core.chat_ai.api.platform.chat_history",
    "chat_ai.api.platform.chat_artifacts": "zatgo_core.chat_ai.api.platform.chat_artifacts",
    "chat_ai.api.platform.get_artifact": "zatgo_core.chat_ai.api.platform.get_artifact",
    "chat_ai.api.platform.chat_events_subscribe": "zatgo_core.chat_ai.api.platform.chat_events_subscribe",
    "chat_ai.api.platform.chat_tools_list": "zatgo_core.chat_ai.api.platform.chat_tools_list",
    "chat_ai.api.platform.chat_plugins_list": "zatgo_core.chat_ai.api.platform.chat_plugins_list",
    "chat_ai.api.platform.chat_connectors_list": "zatgo_core.chat_ai.api.platform.chat_connectors_list",
    "chat_ai.api.platform.chat_connectors_test": "zatgo_core.chat_ai.api.platform.chat_connectors_test",
    "chat_ai.api.platform.cancel_turn": "zatgo_core.chat_ai.api.platform.cancel_turn",
    "chat_ai.api.voice.health": "zatgo_core.chat_ai.api.voice.health",
    "chat_ai.api.voice.profiles": "zatgo_core.chat_ai.api.voice.profiles",
    "chat_ai.api.voice.speak": "zatgo_core.chat_ai.api.voice.speak",
    "tracker.api.v1.activity.active": "zatgo_core.tracker.api.v1.activity.active",
    "tracker.api.v1.activity.activity_types": "zatgo_core.tracker.api.v1.activity.activity_types",
    "tracker.api.v1.activity.start": "zatgo_core.tracker.api.v1.activity.start",
    "tracker.api.v1.activity.pause": "zatgo_core.tracker.api.v1.activity.pause",
    "tracker.api.v1.activity.stop": "zatgo_core.tracker.api.v1.activity.stop",
    "tracker.api.v1.activity.running_now": "zatgo_core.tracker.api.v1.activity.running_now",
    "tracker.api.v1.audit.list_for_doc": "zatgo_core.tracker.api.v1.audit.list_for_doc",
    "tracker.api.v1.audit.feed": "zatgo_core.tracker.api.v1.audit.feed",
    "tracker.api.v1.filters.get_presets": "zatgo_core.tracker.api.v1.filters.get_presets",
    "tracker.api.v1.filters.set_last": "zatgo_core.tracker.api.v1.filters.set_last",
    "tracker.api.v1.filters.save_preset": "zatgo_core.tracker.api.v1.filters.save_preset",
    "tracker.api.v1.filters.delete_preset": "zatgo_core.tracker.api.v1.filters.delete_preset",
    "tracker.api.v1.hierarchy.my_tree": "zatgo_core.tracker.api.v1.hierarchy.my_tree",
    "tracker.api.v1.hierarchy.org_tree": "zatgo_core.tracker.api.v1.hierarchy.org_tree",
    "tracker.api.v1.hierarchy.create_top_member": "zatgo_core.tracker.api.v1.hierarchy.create_top_member",
    "tracker.api.v1.hierarchy.assign_org_member": "zatgo_core.tracker.api.v1.hierarchy.assign_org_member",
    "tracker.api.v1.hierarchy.update_employee_org": "zatgo_core.tracker.api.v1.hierarchy.update_employee_org",
    "tracker.api.v1.hierarchy.seed_demo": "zatgo_core.tracker.api.v1.hierarchy.seed_demo",
    "tracker.api.v1.hierarchy.seed_demo_work": "zatgo_core.tracker.api.v1.hierarchy.seed_demo_work",
    "tracker.api.v1.hierarchy.can_assign": "zatgo_core.tracker.api.v1.hierarchy.can_assign",
    "tracker.api.v1.hierarchy.assign": "zatgo_core.tracker.api.v1.hierarchy.assign",
    "tracker.api.v1.projects.list_projects": "zatgo_core.tracker.api.v1.projects.list_projects",
    "tracker.api.v1.projects.get_project": "zatgo_core.tracker.api.v1.projects.get_project",
    "tracker.api.v1.projects.create_project": "zatgo_core.tracker.api.v1.projects.create_project",
    "tracker.api.v1.projects.add_member": "zatgo_core.tracker.api.v1.projects.add_member",
    "tracker.api.v1.projects.close_project": "zatgo_core.tracker.api.v1.projects.close_project",
    "tracker.api.v1.reports.overview": "zatgo_core.tracker.api.v1.reports.overview",
    "tracker.api.v1.reports.hours_by_project": "zatgo_core.tracker.api.v1.reports.hours_by_project",
    "tracker.api.v1.reports.hours_by_user": "zatgo_core.tracker.api.v1.reports.hours_by_user",
    "tracker.api.v1.reports.hours_by_activity_type": "zatgo_core.tracker.api.v1.reports.hours_by_activity_type",
    "tracker.api.v1.reports.hours_by_task": "zatgo_core.tracker.api.v1.reports.hours_by_task",
    "tracker.api.v1.reports.hours_by_timesheet": "zatgo_core.tracker.api.v1.reports.hours_by_timesheet",
    "tracker.api.v1.reports.hours_detail": "zatgo_core.tracker.api.v1.reports.hours_detail",
    "tracker.api.v1.tasks.list_tasks": "zatgo_core.tracker.api.v1.tasks.list_tasks",
    "tracker.api.v1.tasks.get_task": "zatgo_core.tracker.api.v1.tasks.get_task",
    "tracker.api.v1.tasks.create_task": "zatgo_core.tracker.api.v1.tasks.create_task",
    "tracker.api.v1.tasks.update_status": "zatgo_core.tracker.api.v1.tasks.update_status",
    "tracker.api.v1.tasks.set_progress": "zatgo_core.tracker.api.v1.tasks.set_progress",
    "tracker.api.v1.tasks.submit_for_review": "zatgo_core.tracker.api.v1.tasks.submit_for_review",
    "tracker.api.v1.tasks.approve": "zatgo_core.tracker.api.v1.tasks.approve",
    "tracker.api.v1.tasks.request_rework": "zatgo_core.tracker.api.v1.tasks.request_rework",
    "tracker.api.v1.tickets.list_tickets": "zatgo_core.tracker.api.v1.tickets.list_tickets",
    "tracker.api.v1.tickets.get_ticket": "zatgo_core.tracker.api.v1.tickets.get_ticket",
    "tracker.api.v1.tickets.create_ticket": "zatgo_core.tracker.api.v1.tickets.create_ticket",
    "tracker.api.v1.tickets.assign": "zatgo_core.tracker.api.v1.tickets.assign",
    "tracker.api.v1.timesheets.list_team_drafts": "zatgo_core.tracker.api.v1.timesheets.list_team_drafts",
    "tracker.api.v1.timesheets.submit_team": "zatgo_core.tracker.api.v1.timesheets.submit_team",
    "zatgo_space.api.v1.space.list_catalog": "zatgo_core.zatgo_space.api.v1.space.list_catalog",
    "zatgo_space.api.v1.space.list_sites_usage": "zatgo_core.zatgo_space.api.v1.space.list_sites_usage",
    "zatgo_space.api.v1.space.create_order": "zatgo_core.zatgo_space.api.v1.space.create_order",
    "zatgo_space.api.v1.space.get_order": "zatgo_core.zatgo_space.api.v1.space.get_order",
    "zatgo_space.api.v1.space.update_order_status": "zatgo_core.zatgo_space.api.v1.space.update_order_status",
    "zatgo_space.api.v1.space.update_order_usage": "zatgo_core.zatgo_space.api.v1.space.update_order_usage",
}
