"""/vansalex — the Flutter web build's page (vansalex.html, generated by
scripts/deploy_web_build.sh, not committed). Formerly the vansalex_web app.

Never cached, by Frappe or by the browser. The page is ~1.5 KB, but its
`<base href>` names the current build's versioned asset folder
(/assets/zatgo_core/vansalex/<build-id>/). A cached page would keep a
driver on an old build for hours: Frappe's default for www pages is a
30-minute server-side copy plus browser `max-age=300,
stale-while-revalidate=10800`. The build's own files can then be cached
forever, because every deploy gives them new URLs.
"""

from __future__ import annotations

import frappe

# Read by Frappe's TemplatePage: never store this page in the website cache
# (nor send its default private,max-age=300,stale-while-revalidate headers).
no_cache = 1


def get_context(context):
    from zatgo_core.services.ui_apps import switches

    # The build is compiled for one site's address (FRAPPE_BASE_URL): on a
    # site it doesn't belong to it would talk to that other site.
    if not switches()["vansalex_web"]:
        # Don't let Frappe cache this 404 (website_404): it would outlive
        # switching the page on.
        frappe.local.no_cache = 1
        raise frappe.PageDoesNotExistError
    headers = getattr(frappe.local, "response_headers", None)
    if headers is not None:
        # Always revalidate: cheap for a tiny page, and it is what points the
        # browser at the newest build.
        headers["Cache-Control"] = "no-cache"
    return context
